version: '2'
services:
    php:
        container_name: blog-php
        image: blog-php
        build: ./php
        links:
            - db
        volumes:
            - ${APP_DIR}:/home/app:cached
        network_mode: bridge
    web:
        container_name: blog-web
        image: blog-web
        build: ./web
        links:
            - php
        volumes_from:
            - php
        ports:
            - "80:80"
        network_mode: bridge
    db:
        container_name: blog-db
        image: mariadb:10.4.6
        volumes:
            - ${APP_DB}:/var/lib/mysql
            - ${PWD}/db/etc/mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        network_mode: bridge
